### ISSUE TITLE
Error handling issue

### ISSUE THREAD

**Issue by KanishkM08** [Gargantuan5k/edu-base#3]
You could try to solve the error by setting the ch variable's data type as str instead of int (Line 43 of the last committed code) 
![image](https://github.com/Gargantuan5k/edu-base/assets/78301665/77a07380-4fe1-480b-8dd9-cf89d19169e1)

**Comment by Gargantuan5k** [comment]
will fix by eod

**Comment by Gargantuan5k** [comment]
Resolved in e0e94e0481fbcb3e8c83150974b39d13e337492b
